<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 8/10/18
 * Time: 10:01 AM
 */

namespace App\Form;


use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LoginForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
       $builder
           ->add('_username',EmailType::class,
               [
                   'attr'=>[
                       'id'=>'email',
                       'placeholder'=>'Email'
                   ],
                   'label'=>false
               ])
           ->add('_password',PasswordType::class,[
               'attr'=>[
                   'id'=>'password',
                   'placeholder'=>'Password'
               ],
               'label'=>false
           ]);
    }

   public function configureOptions(OptionsResolver $resolver)
   {
       parent::configureOptions($resolver); // TODO: Change the autogenerated stub
   }


}